### ISSUE TITLE
Release 1.0: Roadmap

### ISSUE THREAD

**Issue by juliotux** [sparc4-dev/astropop#110]
At this point, after 0.9 tag, astropop implementationis ready for 1.0 release. But some work remains.

- [ ] Make the list of documentation needed. Put the list here.
- [ ] Finish the documentation: Work on the documentation of the modules listed here.
- [ ] Increase coverage to 100%: Only some files are not 100% covered yet. Cover them.
  - [ ] py_utils.py
  - [ ] photometry/detection.py
  - [ ] photometry/background.py
  - [ ] photometry/aperture.py
  - [ ] math/reproject.py
  - [ ] math/_deriv.py
  - [ ] image/register.py
  - [ ] image/processing.py
  - [ ] image/imcombine.py
  - [ ] framedata/_compat.py
  - [ ] file_collection.py
  - [ ] astrometry/astrometrynet.py
  - [ ] _db.py
- [ ] Include files for changelog.
